sudo: required

services: 
  - docker

before_install:
  - docker version
  - docker-compose version

script:
  - docker-compose -f local.yml run --rm $(bash <(curl -s https://codecov.io/env)) django ash -c 'pytest --cov=./ && apk update && apk add git && codecov'
